---
title: "Reporting Google Trends - recherches sur des formats de données"
output:
  pdf_document: default
  html_document:
    theme: flatly
date: "`r lubridate::now()`"
params:
  search_terms: !r c("csv", "json", "rdf")
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    message = FALSE,
    warning = FALSE
    )

# Google Trends API
library(gtrendsR)

# Les packages pour graphiques et manipulation de données ----
library(tidyverse)
library(lubridate)
library(tidyquant)

# File System
library(fs)
```

# Les requêtes contenant les termes des formats de fichier suivants :

```{r}
tibble("Search Terms" = params$search_terms) %>% knitr::kable()
```

```{r}
gtrends_lst <- gtrendsR::gtrends(params$search_terms, geo = "FR", time = "today+5-y")
gtrends_lst_all <- gtrendsR::gtrends(params$search_terms, geo = "FR", time = "all")
```

# Evolution sur les cinq dernières années

```{r}
gtrends_lst %>% 
    pluck("interest_over_time") %>% 
    mutate(hits = as.numeric(hits)) %>%
    as_tibble() %>%
    ggplot(aes(date, hits, color = keyword)) +
    geom_line() +
    geom_smooth(span = 0.3, se = FALSE) +
    theme_tq() +
    scale_color_tq() +
    labs(title = "Part des requêtes contenant le mot clé - évolution sur cinq ans - France")
```

\newpage

# Evolution depuis 2004

```{r}
gtrends_lst_all %>% 
    pluck("interest_over_time") %>% 
    mutate(hits = as.numeric(hits)) %>%
    as_tibble() %>%
    ggplot(aes(date, hits, color = keyword)) +
    geom_line() +
    geom_smooth(span = 0.3, se = FALSE) +
    theme_tq() +
    scale_color_tq() +
    labs(title = "Part des requêtes contenant le mot clé - depuis 2004 - France")
```

\newpage

# Les principales requêtes contenant le mot-clé

```{r, fig.height=3}
n_terms <- 10

top_five_related_searches_tbl <- gtrends_lst %>%
    pluck("related_queries") %>%
    as_tibble() %>%
    filter(related_queries == "top") %>%
    mutate(interest = as.numeric(subject)) %>%
    
    select(keyword, value, interest) %>%
    group_by(keyword) %>%
    arrange(desc(interest)) %>%
    slice(1:n_terms) %>%
    ungroup() %>%
    
    mutate(value = as_factor(value) %>% fct_reorder(interest))

top_five_related_searches_tbl %>%
    ggplot(aes(value, interest, color = keyword)) +
    geom_segment(aes(xend = value, yend = 0)) +
    geom_point() +
    coord_flip() +
    facet_wrap(~ keyword, nrow = 1, scales = "free_y") +
    theme_tq() +
    scale_color_tq()
```

